### PR TITLE
This should fix the native browser pwa prompt.

### LINKED ISSUE #113: PWA App Install Prompt
## Expected Behavior

App can be installed using the Browser native PWA implementation.

## Current Behavior

No option is given.

## Possible Solution

Implement it ( see https://developers.google.com/web/fundamentals/app-install-banners )

## Steps to Reproduce (for bugs)

1. Open https://www.manifest.app/
2. Proof it

## Context

Would be nice to have this app as shortcut installed in the system ( be it Windows, Linux, Android, etc. )

## Your Environment

* Environment name and version (nginx 1.9.1): Chrome 79.0.3945.130 (64 bit)
* Operating System and version: Windows 10 OS Version 1909 (Build 18363.592)

### PR DESCRIPTION
**Pull request by mirshko**
## Description

Should fix #113 

## Related Issue

#113 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by jonathontoon — COMMENTED** [review]
Thanks for the PR @mirshko!

Any chance you could add some background to why this change would fix the PWA prompt? My current implementation was based on the [W3C spec](https://www.w3.org/TR/appmanifest/) and the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Manifest) which indicated that _.webmanifest_ is a canonical file type (interchangeable with .json).  

At present, through at least my own testing, Chromium on Windows and Android display the native PWA prompts no problem. But there is no explicit manual trigger created from Manifest (the app) itself.

**Comment by mirshko** [comment]
It was just a thought of perhaps why Chrome wasn’t picking it up. 

Going through the Google Developers PWA manifest bit it suggests to use .json and doesn’t mention .webmanifest anywhere. Will need to test locally.

**Comment by mirshko** [comment]
Okay this doesn't actually fix it.

My bad. It might be related to the service worker. Will look into this.

**Comment by mirshko** [comment]
https://developers.google.com/web/fundamentals/app-install-banners/#criteria heres the criteria

**Comment by jonathontoon** [comment]
@mirshko no worries. 

FWIW this is what I currently get on Brave (Chromium 79) for Android. 



It _was_ working for me too on Chromium (79) for Windows but for whatever reason I can't get the prompt to display again, even after flushing the cache. 

In my experience thus far I've found the service worker to be incredibly fickle, so if you have any ideas for better reliability I'm all ears. ✌️

**Comment by jonathontoon** [comment]
@mirshko going to close this off for now, but happy to review any future PRs or ideas regarding this issue!

**Pull request closed without merging**
